import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { SiGmail } from "react-icons/si";
import { FaGithub, FaLinkedin  } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Naing Lin Maung",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />

        <Navbar />
        <div className="min-h-[78vh]">
          {children}
        </div>
        <footer className="text-gray-500 text-center mt-5 mb-5">
          <div className="flex items-center justify-center gap-7">
            <a href="mailto:nlmnever2@gmail.com" target="_blank" rel="noopener noreferrer">
              <div className="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center">
                <SiGmail size={20} color="black"/>
              </div>
            </a>
            <a href="https://github.com/Npvpr" target="_blank" rel="noopener noreferrer">
              <div className="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center">
                <FaGithub  size={25} color="black"/>
              </div>
            </a>
            <a href="https://www.linkedin.com/in/naing-lin-maung/" target="_blank" rel="noopener noreferrer">
              <div className="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center">
                <FaLinkedin  size={24} color="black"/>
              </div>
            </a>
          </div>
          <div className="mt-5">
            Copyright © 2025 Naing Lin Maung - All Rights Reserved. All content
            and trademarks property of their respective owners.{" "}
          </div>
        </footer>
      </body>
    </html>
  );
}
